### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by aamatthews** [josephhardinee/PyDisdrometer#10]
If possible, it would be useful to pick the temperature used, as well as the times used in analysis.

**Comment by josephhardinee** [comment]
The first part of this has been implemented in commit 26f1db7b6f. I'll work on the second part this weekend, as it should not be too difficult of a fix.

**Comment by josephhardinee** [comment]
Can you split the time selection out into a separate issue as it requires a bit of a larger change. In the meantime I'm going to close this issue as the temperature selection has been implemented.
