### ISSUE TITLE
W band scattering fails

### ISSUE THREAD

**Issue by aamatthews** [josephhardinee/PyDisdrometer#18]
I have been trying to scatter particles at W band and it fails (kernel dies, or python restarts). I have tried narrowing it down to a particular drop size but have had no luck. I have attached a "short" file from the RACORO field campaign of a DSD of just one time step that failed (this must be read in using read_racoro, which I just submitted a pull request for). I also tested the W-band scattering on an APU file from IFloodS, and it failed as well. Do you know what is causing this failure?
[IFloodS_APU11_2013_0529_dsd.txt](https://github.com/josephhardinee/PyDisdrometer/files/75740/IFloodS_APU11_2013_0529_dsd.txt)
[racoro2ds_short.txt](https://github.com/josephhardinee/PyDisdrometer/files/75743/racoro2ds_short.txt)

**Comment by josephhardinee** [comment]
This has been fixed by commit 3e49291d595ed158de70e6731ba0595123184e3f  .
