### ISSUE TITLE
Import 

### ISSUE THREAD

**Issue by godofyoga** [josephhardinee/PyDisdrometer#21]
File "/home/yogesh/anaconda/lib/python2.7/site-packages/pydisdrometer/__init__.py", line 12, in <module>
    from . import partition

ImportError: cannot import name partition

**Comment by josephhardinee** [comment]
Yogesh, 
Is this still an issue with the newest version of PyDisdrometer, I believe it should have been resolved.

**Comment by godofyoga** [comment]
i reinstall pydisdrometer  and now It is resolve
