### ISSUE TITLE
calculate slope coefficient(Λ)

### ISSUE THREAD

**Issue by godofyoga** [josephhardinee/PyDisdrometer#30]
I want to calculate and plot slope coefficient of DSD.I have tried with moments method this way is it useful?

 self.fields['mslope'] = {'data': np.zeros(len(self.time))}            
self.fields['mslope']['data'] = self._calculate_mslope(self.Nd[t])
    def _calculate_mslope(self):
        G=np.divide(self._calc_mth_moment(3)**2,np.multiply(self._calc_mth_moment(2),self._calc_mth_moment(4)))
       mslope = np.divide(self._calc_mth_moment(2),self._calc_mth_moment(3))*(G/(1.0-G))
        
        return mslope

**Comment by nguy** [comment]
This is a pretty classic approach for analysis. We are currently working on implementing these types of calculations along with others in an large update we'll roll out in the near future.

**Comment by josephhardinee** [comment]
PyDisdrometer can estimate mu and D0. From those you can calculate lambda with $\lambda = (3.67 + \mu)/D_0$. Alternatively, it may sometimes be more stable to use Dm. You can use Dm and mu to estimate Lambda with $\Lambda = (4+\mu)/D_m$

**Comment by josephhardinee** [comment]
If this does not answer your question, feel free to reopen the issue, but I will close it for now.
