### ISSUE TITLE
ts_utility

### ISSUE THREAD

**Issue by scollis** [josephhardinee/PyDisdrometer#43]
Python3.5 anaconda 
install from git clone 
Getting error:
```
/Users/scollis/anaconda/envs/pyart35/lib/python3.5/site-packages/PyDisdrometer-0.1.15.1-py3.5.egg/pydisdrometer/utility/__init__.py in <module>()
----> 1 from ts_utility import rolling_window

ImportError: No module named 'ts_utility'
```
<img width="1058" alt="screenshot 2016-12-07 11 41 15" src="https://cloud.githubusercontent.com/assets/825351/20979351/37f93cb2-bc72-11e6-944e-5456dae24e70.png">

**Comment by josephhardinee** [comment]
We're unfortunately stuck on 2.7. I'm partway through porting it over to 3.5.

**Comment by scollis** [comment]
Thanks Joe.. I will roll back to 2.7

**Comment by josephhardinee** [comment]
The most recent pull request should fix this now. I'm going to go ahead and close this, but if it does not resolve the issue, please reopen it.
