### ISSUE TITLE
Not Fully Self Describing

### ISSUE THREAD

**Issue by scollis** [josephhardinee/PyDisdrometer#6]
Insofar as I can tell the data model is not full self describing..

I think we need a self.time_start (as a datetime object) and a self.location = lat,lon

while these could go in notes I think basic usability needs them to be exposed on the base class.

**Comment by josephhardinee** [comment]
I believe this issue has been fully addressed, so I'm going to close it. Let me know if I'm missing something you need, or it did not adequately address your issue and feel free to re-open it.
