### ISSUE TITLE
Support for 2DS/HVPS instrument data

### ISSUE THREAD

**Issue by aamatthews** [josephhardinee/PyDisdrometer#8]
This is now the 2DS only issue.

It would be great if a reader could be added to read in and process 2DS and HVPS .txt files, as these have similar measurements to disdrometers.

2DS: This is split into 2 files, one for Horizontal and one for Vertical, .txt file
-Time is recorded in seconds since 00 UTC, dividing by 3600. puts it into hours.
-The concentration column is the total concentration of drops at that particular time.
-All columns where the header begins C: are the concentrations of drops in each bin, in #/L/um. 
-The spread of the bins is variable.
I believe the data is also tab separated. The example shown I poorly converted to an excel spreadsheet to get a better image of the headers.
![2ds_data_image](https://cloud.githubusercontent.com/assets/2659253/7186000/82462108-e41b-11e4-827e-30dba376539a.png)

HVPS: Vertical only, .txt file
Similar columns and locations to the 2DS data, but the bin sizes are different, as this instrument measures larger particles.

It would be nice if temperature could be set manually, as well as the time chosen to evaluate. Choosing the times to start and end evaluation would allow the user to choose only the time period where the drops were liquid.

**Comment by josephhardinee** [comment]
Can you attach one of the actual files as well please?(Or a link to an actual file)

**Comment by aamatthews** [comment]
https://www.dropbox.com/s/dkak6qezwemqlfu/2DS_20150205a_H_M1ice.txt.gz?dl=0
Here is the link to one of the 2DS Horizontal files. It says ice, but that was just the processing mode. There are times of just liquid drops present.

**Comment by josephhardinee** [comment]
Also can you split these into two different issues on here, this will make it a little easier for each PR to address one at a time.

**Comment by aamatthews** [comment]
Do you mean split by file type (2DS and HVPS separate), or by reader and choosing time/temperature?

**Comment by aamatthews** [comment]
Also, the final bin for the C: category is set by the file as 'inf', for binning purposes in the past, we have set this to be 4000 for 2DS.

**Comment by josephhardinee** [comment]
This is addressed in commit ab064fd. Closing.
