### ISSUE TITLE
HVPS reader

### ISSUE THREAD

**Issue by aamatthews** [josephhardinee/PyDisdrometer#9]
Data is similar to the 2DS data in set up (similar columns and units). However, the bin headers are broken, and must be read in from a separate file.
HVPS data:
https://www.dropbox.com/s/qdb9y0ts4nf8y05/HVPS_20150205a_V_M1ice.txt.gz?dl=0
HVPS bins:
https://www.dropbox.com/s/tmui3kpk6lrywuz/HVPS_Bins.csv?dl=0

**Comment by josephhardinee** [comment]
This is addressed in commit ab064fd. Closing.
